# This is an example neoforge.mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml

# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the FML version. This is currently 2.
loaderVersion="2" # Set your actual loader version if necessary

# The license for your mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"

# A URL to refer people to when problems occur with this mod
# issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="enderbeam" #mandatory (Ensure this is the same as your @Mod annotation in your code)

# The version number of the mod
version="0.1.3" #mandatory (Replace with your actual mod version)

# A display name for the mod
displayName="EnderBeam" #mandatory (Your mod's display name)

# A URL to query for updates for this mod. See the JSON update specification https://docs.neoforged.net/docs/misc/updatechecker/
# updateJSONURL="https://change.me.example.invalid/updates.json" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
# displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional

# A file name (in the root of the mod JAR) containing a logo for display
# logoFile="examplemod.png" #optional

# A text field displayed in the mod UI
# credits="" #optional

# A text field displayed in the mod UI
authors="Makla" #optional (List the authors of the mod)

# The description text for the mod (multi-line!) (#mandatory)
description='''Satellitical laser mining using small rockets and lots of power.'''

# The [[mixins]] block allows you to declare your mixin config to FML so that it gets loaded.
# [[mixins]]
# config="${mod_id}.mixins.json"

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
# [[accessTransformers]]
# file="META-INF/accesstransformer.cfg"

# The coremods config file path is not configurable and is always loaded from META-INF/coremods.json

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.enderbeam]] #optional (Ensure this is the correct modId, in this case, 'enderbeam')
# the modid of the dependency
modId="neoforge" #mandatory
# The type of the dependency. Can be one of "required", "optional", "incompatible" or "discouraged" (case insensitive).
type="required" #mandatory
# The version range of the dependency
versionRange="[1.0,)" #mandatory (Replace with actual version range if needed)
# An ordering relationship for the dependency.
ordering="NONE"
# Side this dependency is applied on - BOTH, CLIENT, or SERVER
side="BOTH"

# Here's another dependency
[[dependencies.enderbeam]]
modId="minecraft"
type="required"
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="[1.19,)" # Replace with actual version range for Minecraft
ordering="NONE"
side="BOTH"

# Features are specific properties of the game environment, that you may want to declare you require.
# This example declares that your mod requires GL version 3.2 or higher.
#[features.enderbeam]
# openGLVersion="[3.2,)"
